### ISSUE TITLE
Notes about licensing 

### ISSUE THREAD

**Issue by nosoop** [chrisliatas/pubsub-monitor#9]
Hi &mdash; I'm not a lawyer and this isn't legal advice, but I did notice your mention of having to release the project under GPLv3.

My understanding based on the GPL FAQ entries [(1)](https://www.gnu.org/licenses/gpl-faq.html#LinkingWithGPL) [(2)](https://www.gnu.org/licenses/gpl-faq.html#WhatIsCompatible) and working under a framework whose compiled outputs are always GPL-licensed, is that the combined work must be released under the GPL, but the rest of the work may be under [any other compatible licenses](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses).

So you can release the Python components you've written under Apache License 2.0, but any users using the combined work with the infinite scroll plugin would need to obey GPLv3.

**Comment by chrisliatas** [comment]
Ahh, yes good catch! It has been a few years since I created this, with lesser knowledge on licensing. Thanks!
